language: c
os: linux
dist: focal
branches:
  only:
    - master
services:
  - docker
compiler:
  - gcc
cache:
  directories:
    - docker_images
before_install:
  - echo "deb http://ppa.launchpad.net/snaipewastaken/ppa/ubuntu cosmic main" | sudo tee -a ${TRAVIS_ROOT}/etc/apt/sources.list >/dev/null
  - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com CE6500E9003E6E24
  - sudo apt-get -q update
  - sudo apt-get -y install pkg-config doxygen openssl zlib1g-dev build-essential criterion-dev gcovr graphviz cppcheck
  - docker load -i docker_images/images.tar || true
before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)
stages:
  - cppcheck
  - docs
  - criterion
  - autobahn
jobs:
  include:
    - stage: cppcheck
      script: 
        - cppcheck --language=c -f -q --enable=warning,performance,portability --std=c11 --error-exitcode=1 -itest -Iinclude -Iextensions -Isubprotocols . >build.log 2>&1 || (cat build.log && rm build.log && exit 1)

    - stage: docs 
      script: 
        - ./scripts/travis.sh
        - make docs 
      deploy:
        strategy: git
        provider: pages
        cleanup: false
        skip_cleanup: true
        local_dir: generated
        github_token: $GH_REPO_TOKEN
        keep_history: true
        project_name: WSServer
        on:
          branch: master

    - stage: criterion
      script: 
        - ./scripts/travis.sh
        - make test
      deploy:
        strategy: git
        provider: pages
        cleanup: false
        skip_cleanup: true
        local_dir: generated
        github_token: $GH_REPO_TOKEN
        keep_history: true
        project_name: WSServer
        on:
          branch: master

    - stage: autobahn 
      script: 
        - ./scripts/travis.sh
        - make autobahn
      deploy:
        strategy: git
        provider: pages
        cleanup: false
        skip_cleanup: true
        local_dir: generated
        github_token: $GH_REPO_TOKEN
        keep_history: true
        project_name: WSServer
        on:
          branch: master
